// Generated by CoffeeScript 1.4.0
(function() {

  define(["d3"], function(d3) {
    var alphabet, height, shuffle, svg, update, width;
    update = function(data) {
      var text;
      text = svg.selectAll("text").data(data, function(d) {
        return d;
      });
      text.attr("class", "update").transition().duration(750).attr("x", function(d, i) {
        return i * 32;
      });
      text.enter().append("text").attr("class", "enter").attr("dy", ".35em").attr("y", -60).attr("x", function(d, i) {
        return i * 32;
      }).style("fill-opacity", 1e-6).text(function(d) {
        return d;
      }).transition().duration(750).attr("y", 0).style("fill-opacity", 1);
      return text.exit().attr("class", "exit").transition().duration(750).attr("y", 60).style("fill-opacity", 1e-6).remove();
    };
    shuffle = function(array) {
      var i, m, t;
      m = array.length;
      t = void 0;
      i = void 0;
      while (m) {
        i = Math.floor(Math.random() * m--);
        t = array[m];
        array[m] = array[i];
        array[i] = t;
      }
      return array;
    };
    alphabet = "abcdefghijklmnopqrstuvwxyz".split("");
    width = 824;
    height = 500;
    svg = d3.select(".container").append("svg").attr("width", width).attr("height", height).append("g").attr("transform", "translate(32," + (height / 2) + ")");
    update(alphabet);
    return setInterval((function() {
      return update(shuffle(alphabet).slice(0, Math.floor(Math.random() * 26)).sort());
    }), 1500);
  });

}).call(this);
